insert into hobbies value 
('',1,'Arts martiaux'), 
('',1,'Athlétisme'), 
('',1,'Auto-moto'), 
('',1,'Cyclisme'), 
('',1,'Equitation'), 
('',1,'Fitness'), 
('',1,'Body-building'), 
('',1,'Football'), 
('',1,'Basketball'), 
('',1,'Hockey sur glace'), 
('',1,'Football américain'), 
('',1,'Golf'), 
('',1,'Rugby'), 
('',1,'Tennis'), 
('',1,'Sports aériens'), 
('',1,'Sports aquatiques'), 
('',1,'Sports d\'hiver'),
('',1,'Sports d\'équipe'),
('',2,'Tourisme'), 
('',2,'Camping'), 
('',2,'Trekking'), 
('',3,'Théatre'), 
('',3,'Littérature'), 
('',3,'Histoire'), 
('',4,'Peinture'), 
('',4,'BD'), 
('',4,'Dessin animé'), 
('',5,'Couture'), 
('',5,'Broderie'), 
('',5,'Bricolage'), 
('',5,'Tapisserie'), 
('',5,'Artisanat'), 
('',5,'Décoration'), 
('',6,'Instruments'), 
('',6,'Variété française'),
('',6,'Pop rock, Indé'),
('',6,'Rap'), 
('',6,'R&B'),
('',6,'Soul'),
('',6,'Funk'), 
('',6,'Electro'),
('',6,'Hard rock, Métal'),
('',6,'Compilations'), 
('',6,'BO, Musiques de film'),
('',6,'Jazz'),
('',6,'Blues'), 
('',7,'Mobiles / Tablettes'),
('',8,'Modélisme'),
('',9,'Jeux de société'),
('',9,'Jeux vidéos et consoles'),
('',9,'Jeux de rôle'),
('',9,'Paintball'),
('',10,'Biologie'),
('',10,'Energie'),
('',10,'Mathématique'),
('',10,'Physique'),
('',10,'Chimie'),
('',11,'Photo'),
('',11,'Vidéo'),
('',11,'Surf internet'),
('',11,'Infographie'),
('',11,'Webdesign'),
('',11,'Programmation'),
('',11,'Modélisme'),
('',11,'Jeux de construction'),
('',11,'Philatélie'),
('',11,'Tatoos'),
('',11,'Mot-croisés'),
('',11,'Bricolage / Décoration'),
('',12,'Joinglerie'),
('',12,'Danse de rue'),
('',12,'Danse'),
('',12,'Pêche / Chasse'),
('',12,'Hippisme'),
('',13,'Patisserie'),
('',13,'Cuisine'),
('',14,'Série TV'),
('',13,'Enfants, Jeunesse'),
('',13,'Fantastique, Science-fiction'),
('',13,'Drame, Emotion'),
('',13,'Action, Policier'),
('',13,'Comédie'),
('',13,'Japanimation'),
('',13,'Documentaires'),
('',14,'Radio jeunesse'),
('',14,'Radios musicales'),
('',14,'Radio d\'information'),
('',15,'Vêtements'),
('',15,'Chaussures'),
('',16,'Film d\'aventure'),
('',16,'Film d\'action'),
('',16,'Film d\'espionnage'),
('',16,'Film de guerre'),
('',16,'Film fantastique'),
('',16,'Film de romance'),
('',16,'Film noir'),
('',16,'Film policier'),
('',16,'Comédie'),
('',16,'Biopic'),
('',16,'Western'),
('',16,'Thriller'),
('',17,'Massage'),
('',17,'Yoga'),
('',18,'Luxe'),
('',18,'Mode'),
('',19,'Collections'),
('',19,'Auto-tuning'),
('',19,'Auto'),
('',19,'Moto'),
('',19,'Bateaux / Voiles'),
('',19,'Tracteur / Camions / Bus'),
('',20,'Animaux domestiques'),
('',20,'Animaux sauvages'),
('',20,'Ecologie'),
('',20,'Jardinage'),
('',20,'Aménagement'),
('',20,'Flore'),
('',20,'Faune'),
('',21,'Astrologie - Paranormal'),
('',21,'Psycho'),
('',21,'Roman photo'),
('',21,'Parc d\'attraction'),
('',21,'Casino');
