_home:
    pattern:  /
    defaults: { _controller: HeySiteBundle:Login:login }
    
_contact:
    pattern:  /contact
    defaults: { _controller: HeySiteBundle:Contact:index }
    
_footer:
    pattern:  /footer
    defaults: { _controller: HeySiteBundle:Event:footer }
_quicksign:
    pattern:  /quicksign
    defaults: { _controller: HeySiteBundle:Login:quicksign }

_install:
    pattern:  /install
    defaults: { _controller: HeyAccountBundle:Install:default }
    
_event_show:
    pattern:  /event/show/{id}
    defaults: { _controller: HeySiteBundle:Event:show }
    
_event_section_contain:
    pattern:  /event/section/contain
    defaults: { _controller: HeySiteBundle:Event:contain }

_event_search:
    pattern:  /event/search
    defaults: { _controller: HeySiteBundle:Event:search }    

_account_login:
    pattern:  /account/login
    defaults: { _controller: HeySiteBundle:Login:login }

_account_logout:
    pattern:  /account/logout
    defaults: { _controller: HeySiteBundle:Login:logout }

_account_dashboard:
    pattern:  /account/dashboard
    defaults: { _controller: HeyAccountBundle:Dashboard:index }
    
_account_picture:
    pattern:  /account/picture
    defaults: { _controller: HeyAccountBundle:Picture:index }

_account_picture_crop:
    pattern:  /account/picture/crop
    defaults: { _controller: HeyAccountBundle:Picture:crop }
    
_account_profil_edit:
    pattern:  /account/profil
    defaults: { _controller: HeyAccountBundle:Profil:edit }
    
_account_profil_hobbies_add:
    pattern:  /account/profil/hobbies/add
    defaults: { _controller: HeyAccountBundle:Profil:addHobbies }
    
_account_profil_hobbies_del:
    pattern:  /account/profil/hobbies/del/{id}
    defaults: { _controller: HeyAccountBundle:Profil:delHobbies }

_account_logincheck:
    pattern:  /account/logincheck

_account_event_etapemenu:
    pattern:  /account/event/etapemenu
    defaults: { _controller: HeyAccountBundle:Event:etapemenu } 
    
_account_event_create:
    pattern:  /account/event/create
    defaults: { _controller: HeyAccountBundle:Event:create } 

_account_event_create_date:
    pattern:  /account/event/create/date
    defaults: { _controller: HeyAccountBundle:Event:createDate } 

_account_event_edit:
    pattern:  /account/event/edit/{id}
    defaults: { _controller: HeyAccountBundle:Event:edit } 

_account_ajax_cp:
    pattern:  /account/ajax/cp
    defaults: { _controller: HeyAccountBundle:Ajax:cp } 

_ajax_is_username_exist:
    pattern:  /ajax/isusernameexist/{username}
    defaults: { _controller: HeyAccountBundle:Ajax:isUsernameExist, username : '' } 
    requirements:
        username: .*
    
_ajax_is_email_exist:
    pattern:  /ajax/isemailexist/{email}
    defaults: { _controller: HeyAccountBundle:Ajax:isEmailExist, email : '' } 
    requirements:
        email: .*

_ajax_is_valid_mdp:
    pattern:  /ajax/isvalidmdp/{password}
    defaults: { _controller: HeyAccountBundle:Ajax:isValidMdp, password : '' } 
    requirements:
        password: .*
    
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
