_event_show:
    pattern:  /event/show
    defaults: { _controller: HeySiteBundle:Event:show }

_account_event_create:
    pattern:  /account/event/create
    defaults: { _controller: HeyAccountBundle:Event:create } 

_account_event_edit:
    pattern:  /account/event/edit/{id}
    defaults: { _controller: HeyAccountBundle:Event:edit } 
    
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
