_events:
    pattern:  /
    defaults: { _controller: HeyMyEventsBundle:Default:index }

_events_show:
    pattern:  /event/show
    defaults: { _controller: HeySiteBundle:Event:show }
    
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
