<?php

namespace Hey\AccountBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccounthobbiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccounthobbiesRepository extends EntityRepository
{
}
