<?php

namespace Hey\AccountBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository {

    public function search($word = null) {
       
        $dql = "SELECT e FROM HeyAccountBundle:Event e
		where e.name like '%".$word."%' or e.presentation like '%".$word."%'
        	order by e.date_created desc";


        return $this->getEntityManager()
                        ->createQuery($dql)
                        ->getResult();
    }

}
