<?php

namespace Hey\AccountBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostalcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalcodeRepository extends EntityRepository
{
	
}