<?php

namespace Hey\AccountBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SociallinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SociallinkRepository extends EntityRepository
{
}
